name: Test

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3

        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      - run: |
          sudo apt update
          sudo apt install -y python3-colcon-common-extensions
          colcon build --symlink-install

      - run: bash -xv ./test/test_todo_reminder.sh

