name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container:
      image: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Test
        shell: bash
        run: |
          rsync -av ./ /root/ros2_ws/src/todo_reminder/
          cd /root/ros2_ws
          source /opt/ros/humble/setup.bash
          colcon build --symlink-install
          source install/setup.bash

          ros2 run todo_reminder todo_reminder &
          TODO_REM_PID=$!
          sleep 2
          bash -xv ./src/todo_reminder/test/test.bash /root
          kill $TODO_REM_PID
